// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TweetSentimentAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(0)]
        public bool Label { get; set; }


        [ColumnName("User ID"), LoadColumn(1)]
        public float User_ID { get; set; }


        [ColumnName("Date"), LoadColumn(2)]
        public string Date { get; set; }


        [ColumnName("NO_QUERY"), LoadColumn(3)]
        public string NO_QUERY { get; set; }


        [ColumnName("User Name"), LoadColumn(4)]
        public string User_Name { get; set; }


        [ColumnName("Tweet"), LoadColumn(5)]
        public string Tweet { get; set; }


    }
}
